### ISSUE TITLE
java.lang.IllegalStateException at android.media.MediaCodec.dequeueOutputBuffer

### ISSUE THREAD

**Issue by liyzay** [ypresto/android-transcoder#19]
> java.lang.IllegalStateException
at android.media.MediaCodec.dequeueOutputBuffer(Native Method)
at net.ypresto.androidtranscoder.engine.VideoTrackTranscoder.drainDecoder(VideoTrackTranscoder.java:171)
at net.ypresto.androidtranscoder.engine.VideoTrackTranscoder.stepPipeline(VideoTrackTranscoder.java:107)
at net.ypresto.androidtranscoder.engine.MediaTranscoderEngine.runPipelines(MediaTranscoderEngine.java:191)
at net.ypresto.androidtranscoder.engine.MediaTranscoderEngine.transcodeVideo(MediaTranscoderEngine.java:97)

/**
     * Dequeue an output buffer, block at most "timeoutUs" microseconds.
     * Returns the index of an output buffer that has been successfully
     * decoded or one of the INFO_* constants.
     * @param info Will be filled with buffer meta data.
     * @param timeoutUs The timeout in microseconds, a negative timeout indicates "infinite".
     * @**throws IllegalStateException if not in the Executing state**,
     *         **or codec is configured in asynchronous mode.**
     * @throws MediaCodec.CodecException upon codec error.
     */
    @OutputBufferInfo
    public final int dequeueOutputBuffer(...){}

**Comment by ypresto** [comment]
More information is needed.
Tell me what device / SoC / OS is used for reproduce.
