### ISSUE TITLE
"Got non SPS NAL data" exception

### ISSUE THREAD

**Issue by spiritedRunning** [ypresto/android-transcoder#27]
I debugged and got sourceBuffer's backingArray content is:
0 0 0 1 39 66 -32 30 -115 104 10 3 -38 108 -128 0 0 3 0 -128 0 0 15 7 -118 17 80

so sourceBuffer[4] is not equal 103,  and it throw "Got non SPS NAL data" exception. 

I tried this same video file in nexus 5, it's backingArray is: 
0 0 0 1 103 66 -128 30 -38 2 -128 -10 -128 109 10 19 80

I'm confused that why different devices parse a different csd-0 data? It seems like a bug.

Log is below:

`56:36.120 2821-2832/net.ypresto.androidtranscoder.example W/MemoryDealer: madvise(0x7a34e000, 614400, MADV_REMOVE) returned Operation not supported on transport endpoint
07-29 14:56:36.120 2821-3488/net.ypresto.androidtranscoder.example I/MediaCodec-JNI: throwExceptionAsNecessary err = 0
07-29 14:56:36.130 2821-3488/net.ypresto.androidtranscoder.example E/MediaTranscoder: Fatal error while transcoding, this might be invalid format or bug in engine or Android.
                                                                                      java.lang.IllegalStateException: Got non SPS NAL data.
                                                                                          at net.ypresto.androidtranscoder.utils.AvcCsdUtils.getSpsBuffer(AvcCsdUtils.java:57)
                                                                                          at net.ypresto.androidtranscoder.engine.MediaFormatValidator.validateVideoOutputFormat(MediaFormatValidator.java:37)
                                                                                          at net.ypresto.androidtranscoder.engine.MediaTranscoderEngine$1.onDetermineOutputFormat(MediaTranscoderEngine.java:162)
                                                                                          at net.ypresto.androidtranscoder.engine.QueuedMuxer.onSetOutputFormat(QueuedMuxer.java:66)
                                                                                          at net.ypresto.androidtranscoder.engine.QueuedMuxer.setOutputFormat(QueuedMuxer.java:61)
                                                                                          at net.ypresto.androidtranscoder.engine.VideoTrackTranscoder.drainEncoder(VideoTrackTranscoder.java:207)
                                                                                          at net.ypresto.androidtranscoder.engine.VideoTrackTranscoder.stepPipeline(VideoTrackTranscoder.java:105)
                                                                                          at net.ypresto.androidtranscoder.engine.MediaTranscoderEngine.runPipelines(MediaTranscoderEngine.java:191)
                                                                                          at net.ypresto.androidtranscoder.engine.MediaTranscoderEngine.transcodeVideo(MediaTranscoderEngine.java:97)
                                                                                          at net.ypresto.androidtranscoder.MediaTranscoder$4.call(MediaTranscoder.java:185)
                                                                                          at net.ypresto.androidtranscoder.MediaTranscoder$4.call(MediaTranscoder.java:167)
                                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                          at java.lang.Thread.run(Thread.java:841)`

(Reproduced with Huawei p7 mobile phone)

**Comment by ypresto** [comment]
```java
    // Refer: http://www.cardinalpeak.com/blog/the-h-264-sequence-parameter-set/
    private static final byte AVC_SPS_NAL = 103; // 0<<7 + 3<<5 + 7<<0
```

According to RFC of RTP (https://tools.ietf.org/html/rfc6184), two bits after first 0 (0<<7) stands for nal_rel_idc.

> nal_ref_idc.  A value of 00 indicates that the content of
>             the NAL unit is not used to reconstruct reference pictures
>             for inter picture prediction.

So if it has **non-zero value** this NAL unit should be treated as important.
This transcoder hard-codes 3 == `0b11` for that value but it should accept any non-zero value.
So 39 == `0<<7 + 1<<5 + 7<<0` is valid SPS NAL unit header.

> why different devices parse a different csd-0 data

This is totally strange but it can be pre-processed by transcoder, I think.

**Comment by spiritedRunning** [comment]
I tried process this SPS data in p7 phone, and it works well. Thanks a lot!

**Comment by ypresto** [comment]
@spiritedRunning Could you PR the code used to fix this issue?

**Comment by spiritedRunning** [comment]
I commit a PR to fix this. But I found after using AudioRemixer, it will occasionally throw BufferOverflowException...

**Comment by ypresto** [comment]
It can be different issue caused by #17.
Please open another issue for new one..!
