### ISSUE TITLE
why

### ISSUE THREAD

**Issue by 18801184419** [ypresto/android-transcoder#48]
04-26 02:33:44.819 18120-18164/net.ypresto.androidtranscoder.example D/dalvikvm: GC_FOR_ALLOC freed 248K, 2% free 17010K/17292K, paused 9ms, total 9ms
04-26 02:33:44.819 18120-18164/net.ypresto.androidtranscoder.example E/MediaTranscoder: Fatal error while transcoding, this might be invalid format or bug in engine or Android.
                                                                                        java.nio.BufferOverflowException
                                                                                            at java.nio.ShortBuffer.put(ShortBuffer.java:433)
                                                                                            at net.ypresto.androidtranscoder.engine.AudioRemixer$3.remix(AudioRemixer.java:63)
                                                                                            at net.ypresto.androidtranscoder.engine.AudioChannel.remixAndMaybeFillOverflow(AudioChannel.java:219)
                                                                                            at net.ypresto.androidtranscoder.engine.AudioChannel.feedEncoder(AudioChannel.java:153)
                                                                                            at net.ypresto.androidtranscoder.engine.AudioTrackTranscoder.stepPipeline(AudioTrackTranscoder.java:97)
                                                                                            at net.ypresto.androidtranscoder.engine.MediaTranscoderEngine.runPipelines(MediaTranscoderEngine.java:192)
                                                                                            at net.ypresto.androidtranscoder.engine.MediaTranscoderEngine.transcodeVideo(MediaTranscoderEngine.java:97)
                                                                                            at net.ypresto.androidtranscoder.MediaTranscoder$4.call(MediaTranscoder.java:184)
                                                                                            at net.ypresto.androidtranscoder.MediaTranscoder$4.call(MediaTranscoder.java:166)
                                                                                            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                            at java.lang.Thread.run(Thread.java:841)
04-26 02:33:44.939 16828-16828/com.android.documentsui D/dalvikvm: GC_EXPLICIT freed 1116K, 7% free 28318K/30416K, paused 1ms+3ms, total 23ms

**Comment by ypresto** [comment]
There might be gap between video and audio track.
Or it might be because one of code (video or audio) has been stuck (I have no idea for its reason).
Please try device reboot and another video file.
