### ISSUE TITLE
IllegalStateException MediaCodec onfigure()

### ISSUE THREAD

**Issue by Saqrag** [ypresto/android-transcoder#52]
- phone: xiaomi redmi 2A

- Model Number: 2014112

- android version: 4.4.4KTU84P

- MIUI version: MIUI8.7.4.20beta

```
07-27 12:40:17.928 22970-23128/com.zuga.smallvideo E/ACodec: [OMX.qcom.video.decoder.avc] configureCodec returning error -1010
07-27 12:40:17.928 22970-23127/com.zuga.smallvideo E/MediaCodec: Codec reported an error. (omx error 0x80001001, internalError -1010)
07-27 12:40:18.008 22970-23114/com.zuga.smallvideo E/MediaTranscoder: Fatal error while transcoding, this might be invalid format or bug in engine or Android.
                                                                      java.lang.IllegalStateException
                                                                          at android.media.MediaCodec.native_configure(Native Method)
                                                                          at android.media.MediaCodec.configure(MediaCodec.java:262)
                                                                          at net.ypresto.androidtranscoder.engine.VideoTrackTranscoder.setup(VideoTrackTranscoder.java:89)
                                                                          at net.ypresto.androidtranscoder.engine.MediaTranscoderEngine.setupTrackTranscoders(MediaTranscoderEngine.java:172)
                                                                          at net.ypresto.androidtranscoder.engine.MediaTranscoderEngine.transcodeVideo(MediaTranscoderEngine.java:96)
                                                                          at net.ypresto.androidtranscoder.MediaTranscoder$4.call(MediaTranscoder.java:184)
                                                                          at net.ypresto.androidtranscoder.MediaTranscoder$4.call(MediaTranscoder.java:166)
                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                          at java.lang.Thread.run(Thread.java:841)
```

**Comment by Saqrag** [comment]
I found a regular patterns: video size 16:9, went wrong. 4:3 is ok

**Comment by b005t3r** [comment]
@Saqrag so, did you find out what the problem was? Were you able to fix it?
