### ISSUE TITLE
 net.ypresto.androidtranscoder.engine.InvalidOutputFormatException: Video codecs other than AVC is not supported, actual mime type: video/mp4v-es

### ISSUE THREAD

**Issue by wbgopi** [ypresto/android-transcoder#55]
Hi i am got below issue ......Please help me how to solved the problem
Fatal error while transcoding, this might be invalid format or bug in engine or Android.
                                                                                      net.ypresto.androidtranscoder.engine.InvalidOutputFormatException: Video codecs other than AVC is not supported, actual mime type: video/mp4v-es
                                                                                          at net.ypresto.androidtranscoder.engine.MediaFormatValidator.validateVideoOutputFormat(MediaFormatValidator.java:35)
                                                                                          at net.ypresto.androidtranscoder.engine.MediaTranscoderEngine$1.onDetermineOutputFormat(MediaTranscoderEngine.java:162)
                                                                                          at net.ypresto.androidtranscoder.engine.QueuedMuxer.onSetOutputFormat(QueuedMuxer.java:66)
                                                                                          at net.ypresto.androidtranscoder.engine.QueuedMuxer.setOutputFormat(QueuedMuxer.java:61)
                                                                                          at net.ypresto.androidtranscoder.engine.AudioTrackTranscoder.drainEncoder(AudioTrackTranscoder.java:160)
                                                                                          at net.ypresto.androidtranscoder.engine.AudioTrackTranscoder.stepPipeline(AudioTrackTranscoder.java:90)
                                                                                          at net.ypresto.androidtranscoder.engine.MediaTranscoderEngine.runPipelines(MediaTranscoderEngine.java:192)
                                                                                          at net.ypresto.androidtranscoder.engine.MediaTranscoderEngine.transcodeVideo(MediaTranscoderEngine.java:97)
                                                                                          at net.ypresto.androidtranscoder.MediaTranscoder$4.call(MediaTranscoder.java:184)
                                                                                          at net.ypresto.androidtranscoder.MediaTranscoder$4.call(MediaTranscoder.java:166)
                                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                          at java.lang.Thread.run(Thread.java:818)

**Comment by ypresto** [comment]
This could be happen when:

- Input video uses MPEG4 Visual codec.
- This library have chosen not to transcode video.

Latter might be because resolution of input video is already 720p (1280x720) and no down scaling is necessary. While error message is not clear, this kind of error should be ignored.
