### ISSUE TITLE
.MOV file not transcoded

### ISSUE THREAD

**Issue by hiteshpatel0024** [ypresto/android-transcoder#58]
E/MediaTranscoder: Fatal error while transcoding, this might be invalid format or bug in engine or Android.
                                                                        java.nio.BufferOverflowException
                                                                            at java.nio.ByteBuffer.put(ByteBuffer.java:787)
                                                                            at net.ypresto.androidtranscoder.engine.QueuedMuxer.writeSampleData(QueuedMuxer.java:102)
                                                                            at net.ypresto.androidtranscoder.engine.PassThroughTrackTranscoder.stepPipeline(PassThroughTrackTranscoder.java:80)
                                                                            at net.ypresto.androidtranscoder.engine.MediaTranscoderEngine.runPipelines(MediaTranscoderEngine.java:192)
                                                                            at net.ypresto.androidtranscoder.engine.MediaTranscoderEngine.transcodeVideo(MediaTranscoderEngine.java:97)
                                                                            at net.ypresto.androidtranscoder.MediaTranscoder$4.call(MediaTranscoder.java:184)
                                                                            at net.ypresto.androidtranscoder.MediaTranscoder$4.call(MediaTranscoder.java:166)
                                                                            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                            at java.lang.Thread.run(Thread.java:818)``

**Comment by bkatgithub** [comment]
+1

**Comment by rahulapatil** [comment]
Facing the same issue for the .mov file with no audio.
